name: Sample Deploy for GitHub Pages

on:
  pull_request:
    branches:
      - main
      
jobs:
  unity-web-gl-build:
    name: Build for WebGL
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: ${{ runner.os }}-WebGL-library-${{ hashFiles('**/Library/*') }}
          restore-keys: |
            ${{ runner.os }}-WebGL-library-

      - name: Build Projects
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: '2022.3.17f1'
          targetPlatform: WebGL

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Build-WebGL
          path: build/WebGL

      - name: Set enviroments
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          DEPLOY_PATH=pr/${{ github.event.pull_request.number }}/${{ github.event.pull_request.head.sha }}
          echo "DEPLOY_PATH=$DEPLOY_PATH" >> $GITHUB_ENV
          DEPLOY_URL=https://${{ github.repository_owner }}.github.io/$REPO_NAME/$DEPLOY_PATH
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/WebGL/WebGL
          keep_files: true
          destination_dir: ${{ env.DEPLOY_PATH }}
          cname: pwa.cosmic-voyagers.space

      - name: Comment PR with Deploy URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const deploy_url = process.env.DEPLOY_URL;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `ðŸš€ Deploy preview ready: [${deploy_url}](${deploy_url})`
            });
